### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/infografia-Abraham890-1#1]
[Infografia_Abraham_Reyes_Ortiz_6US.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Abraham890-1/files/8054904/Infografia_Abraham_Reyes_Ortiz_6US.pdf)

**Comment by ArturoAngonJose** [comment]
Calificacion: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
